### ISSUE TITLE
ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by dex4er** [sindresorhus/make-dir#3]
```console
$ node
> process.emitWarning = () => { throw new Error('foo') }
[Function]
> require('make-dir')('/tmp/x')
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> repl:1
process.emitWarning = () => { throw new Error('foo') }
                              ^

Error: foo
    at process.emitWarning (repl:1:37)
    at emitWarning (internal/process/promises.js:72:11)
    at emitPromiseRejectionWarnings (internal/process/promises.js:105:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

I suggest to use `util.promisify` instead `pify` (might be polyfill) and then something like:

```js
const fsP = {}

for (const method of [mkdir, 'stat']) {
  fsP[method] = promisify(fs[method])
}
```

**Comment by dex4er** [comment]
https://www.npmjs.com/package/util.promisify
